a.out : Menu.o Insert.o Preorder.o Inorder.o Postorder.o Search.o
	cc Menu.o Insert.o Preorder.o Inorder.o Postorder.o Search.o
Menu.o : Menu.c
	cc -c Menu.c
Insert.o : Insert.c
	cc -c Insert.c
Preorder.o : Preorder.c
	cc -c Preorder.c
Inorder.o : Inorder.c
	cc -c Inorder.c
Postorder.o : Postorder.c
	cc -c Postorder.c
Search.o : Search.c
	cc -c Search.c
