a.out : Menu.o AddLast.o Display.o RDisplay.o DelFirst.o
	cc Menu.o AddLast.o Display.o RDisplay.o DelFirst.o
Menu.o : Menu.c
	cc -c Menu.c
AddLast.o : AddLast.c
	cc -c AddLast.c
Display.o : Display.c
	cc -c Display.c
RDisplay.o : RDisplay.c
	cc -c RDisplay.c
DelFirst.o : DelFirst.c
	cc -c DelFirst.c
